### ISSUE TITLE
Potential lock-up?

### ISSUE THREAD

**Issue by alexellis** [rancher/remotedialer#57] opened 2023-04-27 08:15 UTC
Hi @cmurphy @cbron thanks for your work on remotedialer updating the README and documenting the new flow control mechanism.

We've been using it to help people connect private services to a central Kubernetes cluster and most TCP/HTTP traffic works exactly as expected.

Recently we were told that tcpdump was showing TCP congestion followed by a lock up (non technical term). Vendoring in Darren's pause/resume flow control work apparently made this better. But when running a script to pull in ~ 100MB of data - it only works the first time, then it locks up for the second time we run the script. When running the same test over a remote forwarded SSH tunnel, the script that pulls this data runs multiple times without locking up. The underlying protocol is a form of LDAP.

If we wait 5 minutes, and see the proxied connection close, then the script to pull data can be run again.

Oddly, running iperf3 with 1-2GB of data completes sequentially, over and over without issue with the flow control patch. I've also seen the Rancher and Harvester teams mention uploading 2-5GB ISO images through remotedialer. So this seems to perhaps be related to a slow reader / fast writer?

I've tried enabling metrics and also debug info - but suspect that maybe there's a deadlock where a pause was sent and everything is on hold? The metrics do not show a gauge for pause/resume - if that was added, do you think it would help show if remotedialer had got into a deadlock?

We see dozens if not hundreds of messages like this:

```
time="2023/04/27 08:16:55" level=debug msg="READ    [2] 20440112/20724079 32768 <nil>"
time="2023/04/27 08:16:55" level=debug msg="WRITE 7206386832554118841 RESUME       [2]"
time="2023/04/27 08:16:55" level=debug msg="READ    [2] 20472880/20724079 32768 <nil>"
time="2023/04/27 08:16:55" level=debug msg="READ    [2] 20505648/20724079 32768 <nil>"
time="2023/04/27 08:16:55" level=debug msg="READ    [2] 20538416/20724079 32768 <nil>"
time="2023/04/27 08:16:55" level=debug msg="READ    [2] 20571184/20724079 32768 <nil>"
time="2023/04/27 08:16:55" level=debug msg="READ    [2] 20603952/20724079 32768 <nil>"
time="2023/04/27 08:16:55" level=debug msg="READ    [2] 20636720/20724079 32768 <nil>"
time="2023/04/27 08:16:55" level=debug msg="READ    [2] 20669488/20724079 32768 <nil>"
time="2023/04/27 08:16:55" level=debug msg="READ    [2] 20702256/20724079 32768 <nil>"
time="2023/04/27 08:16:55" level=debug msg="READ    [2] 20724079/20724079 21823 <nil>"
time="2023/04/27 08:16:55" level=debug msg="resetting remotedialer buffer id=2 to zero, old cap 12582912"
time="2023/04/27 08:16:55" level=debug msg="REQUEST 3665852071688446406 DATA         [2]: buffered"
time="2023/04/27 08:16:55" level=debug msg="ONDATA  [2] 20724079/20725256"
time="2023/04/27 08:16:55" level=debug msg="REQUEST 3665852071688446407 DATA         [2]: buffered"
time="2023/04/27 08:16:55" level=debug msg="ONDATA  [2] 20725256/20758024"
time="2023/04/27 08:16:55" level=debug msg="REQUEST 3665852071688446408 DATA         [2]: buffered"
time="2023/04/27 08:16:55" level=debug msg="ONDATA  [2] 20725256/20790792"
```

There's also a large amount of messages saying that the buffer was exceeded when viewing logs on the server.

```
time="2023/04/27 08:16:53" level=debug msg="remotedialer buffer exceeded id=2, length: 4203768"
time="2023/04/27 08:16:53" level=debug msg="ONDATA  [2] 12772400/16976168"
time="2023/04/27 08:16:53" level=debug msg="REQUEST 3665852071688443237 DATA         [2]: buffered"
time="2023/04/27 08:16:53" level=debug msg="remotedialer buffer exceeded id=2, length: 4204963"
time="2023/04/27 08:16:53" level=debug msg="ONDATA  [2] 12772400/16977363"
time="2023/04/27 08:16:53" level=debug msg="REQUEST 3665852071688443238 DATA         [2]: buffered"
time="2023/04/27 08:16:53" level=debug msg="remotedialer buffer exceeded id=2, length: 4206126"
time="2023/04/27 08:16:53" level=debug msg="ONDATA  [2] 12772400/16978526"
time="2023/04/27 08:16:53" level=debug msg="REQUEST 3665852071688443239 DATA         [2]: buffered"
time="2023/04/27 08:16:53" level=debug msg="remotedialer buffer exceeded id=2, length: 4207281"
time="2023/04/27 08:16:53" level=debug msg="ONDATA  [2] 12772400/16979681"
time="2023/04/27 08:16:53" level=debug msg="REQUEST 3665852071688443240 DATA         [2]: buffered"
```

This is what we can see in the metrics:

```
# TYPE session_server_total_add_websocket_session counter
session_server_total_add_websocket_session{clientkey="73372f0260954018b17a522d2701d440",peer="false"} 1
# HELP session_server_total_receive_bytes Total bytes received
# TYPE session_server_total_receive_bytes counter
session_server_total_receive_bytes{clientkey="73372f0260954018b17a522d2701d440"} 1.17589617e+08
# HELP session_server_total_transmit_bytes Total bytes transmitted
# TYPE session_server_total_transmit_bytes counter
session_server_total_transmit_bytes{clientkey="73372f0260954018b17a522d2701d440"} 316234
```

This looks like ~ 117.589617MB received and 300KB sent.

1. Server opens two local ports
2. Client connects to server and remotely forwards two ports to upstreams in its private network
3. Script queries an LDAP daemon running on the server which pulls in ~ 100MB from the two ports
4. 2nd running of script fails - just hangs

The above works multiple times with remote SSH tunnelling.

Any suggestions would be appreciated

**Comment by cmurphy** [comment] 2023-05-03 22:47
Hi @alexellis,

What version of remotedialer are you using? Specifically I'm wondering if you have this commit https://github.com/rancher/remotedialer/pull/46

Would it be possible to get a concise set of steps I could try to use to reproduce this?

> The metrics do not show a gauge for pause/resume - if that was added, do you think it would help show if remotedialer had got into a deadlock?

That might help. It could show if there's an imbalance in pauses and resumes. The place to add that is probably https://github.com/rancher/remotedialer/blob/master/back_pressure.go

**Comment by alexellis** [comment] 2023-06-07 07:26
Hi @cmurphy 

If there's a potential issue with the lock/unlock - perhaps there should be a gauge in remotedialer anyway that can help identify deadlocks?

The user told me they use the [LDAP protocol which supports "abandoning" a request](https://ldap3.readthedocs.io/en/latest/abandon.html). So there may be a case where one client has abandoned one end of the connection and is no longer reading, but the server is still sending data for a period of time until it acknowledges the abandonment.

I'm not sure where to start debugging this or what additional counters/gauges could help pinpoint the issue. This is the first use-case I've run into in several years of remotedialer getting "stuck" without any useful feedback.

**Comment by cmurphy** [comment] 2023-08-07 23:38
Hi @alexellis,

I apologize for the delayed response.

Could you provide the exact remotedialer version you're running?

> If there's a potential issue with the lock/unlock - perhaps there should be a gauge in remotedialer anyway that can help identify deadlocks?

By lock/unlock do you mean pause/resume? Or do you mean the lower level mutexes in the session and other objects? I've started a draft for adding pause/resume metrics [here](https://github.com/rancher/remotedialer/pull/63). I'm afraid adding such metrics for each `.Lock()`/`.Unlock()` might be unusably noisy.

Do you have access to the script that is being used to pull the 100MB and would it be possible to share it?

**Comment by MKlimuszka** [comment] 2024-03-14 16:39
Closing since there isn't enough info for investigation. It can be reopened if more information is provided.

**Closed by MKlimuszka** 2024-03-14 16:39 UTC

**Comment by alexellis** [comment] 2024-03-14 18:03
Thanks. We haven't had any more information from the end-user and will get in touch again.
